### ISSUE TITLE
Run Goatrodeo on Goatrodeo JAR File

### ISSUE THREAD

**Issue by CJ-cmd-byte** [spice-labs-inc/goatrodeo#91]
Steps:. 

1.  Build the Goat Rodeo JAR file
2.  Note path target/scala-.../goatrodeo....jar
3.  Run goatrodeo on path

**Comment by CJ-cmd-byte** [comment]
GitHub Action to run Goat Rodeo completes sucessfully

```yaml
name: Build ADG from JAR

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        cache: 'sbt'

    - name: Set up sbt
      uses: sbt/setup-sbt@v1

    - name: Build Goat Rodeo Package
      run: sbt package

    - name: Set up directories for running Goat Rodeo against the Goat Rodeo package
      run: |
        mkdir -p target/input
        mkdir -p target/output
        cp target/scala-*/goatrodeo*.jar target/input
    - name: Run Goat Rodeo against the Goat Rodeo package
      run: |
        docker run --platform linux/amd64 --quiet --rm --network none \
           --user $(id -u):$(id -g) \
           -v $(pwd)/target/input:/input:ro \
           -v $(pwd)/target/output:/output \
           spicelabs/goatrodeo:0.6.3 \
           -b /input \
           -o /output
```
